### ISSUE TITLE
Issues and suggestions

### ISSUE THREAD

**Issue by nilbuild** [faisalahsan/GotoTop#1]
- I do not think that you should provide the search box. Why would anyone need that when he has scrolled down?
- Your plunker demo is not working. URL contains an extra `/preview` thingy attached to it
- Improve the folder structure a bit. I mean there is no need to provide the Jquery file. Put the demo in it's own folder called demo. And maybe create a separate src folder containing the plugin data.

You may have a look at how I have organized this plugin. 

https://github.com/kamranahmedse/jquery-toast-plugin

**Comment by kamranahmedse** [comment]
Also, why do you have to call the plugin like `$().doSomething({})`? Why not `$.doSomething({})`. Who suggested you to call it `goToUp()` instead of `goUp()` or `goToTop()`?
